// blog-api/controllers/blogController.js

import fs from 'fs';
import path from 'path';
import { getBlogCount, findAllBlogs, findBlogById, findBlogsByUserId, createBlog, findBlogForUpdateOrDelete, deleteBlog, updateBlog } from '../models/blogModel.js';
import { generateTitleImage } from '../utils/generateTitleImage.js';

/**
 * Helper to normalize image URL path for response
 * @param {string} req Express request object
 * @param {string} imagePath Relative path from DB
 * @returns {string|null} Full URL or null
 */
const getFullImageUrl = (req, imagePath) => {
    if (!imagePath) return null;
    const host = req.protocol + '://' + req.get('host');
    // Ensure path is relative and replace backslashes for URL compatibility
    const relativePath = imagePath.replace(/\\/g, '/');
    const uploadsIndex = relativePath.indexOf('uploads/');
    const finalPath = uploadsIndex !== -1 ? relativePath.substring(uploadsIndex) : relativePath;
    
    return `${host}/${finalPath}`;
};

/**
 * [GET] /api/blogs - Get all blogs with pagination.
 */
export const getAllBlogs = async (req, res) => {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 6;
    const offset = (page - 1) * limit;

    try {
        const totalCount = await getBlogCount();
        const totalPages = Math.ceil(totalCount / limit);

        const blogsResult = await findAllBlogs(limit, offset);
        
        res.json({
            blogs: blogsResult.map(row => ({
                ...row,
                username: row.name,
                image_url: getFullImageUrl(req, row.image_url),
            })),
            totalCount,
            totalPages,
            currentPage: page,
        });

    } catch (err) {
        console.error('Error fetching paginated blog posts:', err.message);
        res.status(500).json({ error: 'Internal server error while fetching blogs.' });
    }
};

/**
 * [GET] /api/blogs/:id - Get a single blog post.
 */
export const getBlogById = async (req, res) => {
    const { id } = req.params;

    try {
        const blog = await findBlogById(id);

        if (!blog) {
            return res.status(404).json({ error: 'Blog post not found.' });
        }

        const responseBlog = {
            ...blog,
            image_url: getFullImageUrl(req, blog.image_url),
        };

        res.json(responseBlog);

    } catch (err) {
        if (err.code === '22P02') { 
            return res.status(400).json({ error: 'Invalid blog ID format.' });
        }
        console.error(`Error fetching blog post with ID ${id}:`, err.message);
        res.status(500).json({ error: 'Internal server error while fetching blog post.' });
    }
};


/**
 * [GET] /api/blogs/user - Get all blogs by the authenticated user.
 */
export const getUserBlogs = async (req, res) => {
    try {
        const userId = req.user.userId;
        
        const blogsResult = await findBlogsByUserId(userId);
        
        const blogs = blogsResult.map(blog => ({
            ...blog,
            image_url: getFullImageUrl(req, blog.image_url),
        }));
        
        res.json({ blogs });
    } catch (err) {
        console.error('Error fetching user blogs:', err.message);
        res.status(500).json({ error: 'Failed to fetch your blogs.' });
    }
};

/**
 * [POST] /api/blogs - Create a new blog post.
 */
export const createNewBlog = async (req, res) => {
    const { title, description, content } = req.body; 
    const userId = req.user.userId; 
    
    if (!title || !content) {
        // Clean up uploaded file if validation fails
        if (req.file) {
            fs.unlink(req.file.path, () => {});
        }
        return res.status(400).json({ error: 'Title and content are required fields.' });
    }
    
    let imagePath = null;
    
    try {
        if (req.file) {
            // Use the relative path generated by Multer
            const fullPath = req.file.path.replace(/\\/g, '/');
            const uploadsIndex = fullPath.indexOf('uploads/');
            imagePath = uploadsIndex !== -1 ? fullPath.substring(uploadsIndex) : fullPath;
            console.log("Relative uploaded file path:", imagePath);
        } else {
            // Generate image if none uploaded
            imagePath = await generateTitleImage(title);
            if (!imagePath) {
                console.error('Failed to generate title image');
                return res.status(500).json({ error: 'Failed to generate title image' });
            }
        }

        // Create blog in DB (Model call)
        const newBlog = await createBlog({ title, description, content, imagePath, userId });
        
        res.status(201).json(newBlog);
    } catch (err) {
        console.error('Error creating new blog post:', err.message);
        // Clean up uploaded file in case of DB error
        if (req.file) {
            fs.unlink(req.file.path, () => {});
        }
        res.status(500).json({ error: 'Internal server error while creating blog post.' });
    }
};

/**
 * [PUT] /api/blogs/:id - Update a blog post.
 */
export const updateExistingBlog = async (req, res) => {
    const { id: blogId } = req.params;
    const userId = req.user.userId;
    const { title, description, content, clear_image } = req.body; 

    if (!title || !content) {
        if (req.file) fs.unlink(req.file.path, () => {}); 
        return res.status(400).json({ error: 'Title and content are required fields for update.' });
    }

    let oldImagePath = null;
    let newImagePath = undefined; // Use undefined to signify 'no change'

    try {
        // 1. Check ownership and retrieve old image path
        const checkResult = await findBlogForUpdateOrDelete(blogId);
        if (!checkResult) {
            if (req.file) fs.unlink(req.file.path, () => {}); 
            return res.status(404).json({ error: 'Blog post not found.' });
        }

        const postOwnerId = checkResult.user_id;
        if (postOwnerId !== userId) {
            if (req.file) fs.unlink(req.file.path, () => {}); 
            return res.status(403).json({ error: 'Permission denied. You can only update your own posts.' });
        }

        oldImagePath = checkResult.image_url;
        let shouldDeleteOldImage = false;

        // 2. Determine the new image path
        if (req.file) {
            // A new file was uploaded
            const fullPath = req.file.path.replace(/\\/g, '/');
            const uploadsIndex = fullPath.indexOf('uploads/');
            newImagePath = uploadsIndex !== -1 ? fullPath.substring(uploadsIndex) : fullPath;
            shouldDeleteOldImage = true;

        } else if (clear_image === 'true') {
            // User explicitly cleared the image, generate a new one
            newImagePath = await generateTitleImage(title);
            if (!newImagePath) {
                return res.status(500).json({ error: 'Failed to generate title image' });
            }
            shouldDeleteOldImage = true;
        } 
        // Else: newImagePath remains undefined, signifying no change to image_url

        // 3. Update DB (Model call)
        const updatedBlog = await updateBlog({ 
            blogId, 
            title, 
            description, 
            content, 
            newImagePath, 
            userId 
        });
        console.log(updatedBlog);

        // 4. Delete old file if necessary
        if (shouldDeleteOldImage && oldImagePath && fs) {
            // The old image path in the DB should be deleted
            const absoluteOldImagePath = path.isAbsolute(oldImagePath) 
                ? oldImagePath 
                : path.join(path.resolve(), oldImagePath);
                
            fs.unlink(absoluteOldImagePath, err => {
                if (err) console.error(`Failed to delete old file: ${absoluteOldImagePath}`, err);
            });
        }
        
        res.status(200).json(updatedBlog);
    } catch (err) {
        console.error('Error updating blog post:', err.message);
        if (req.file) fs.unlink(req.file.path, () => {});
        res.status(500).json({ error: 'Internal server error while updating blog post.' });
    }
};

/**
 * [DELETE] /api/blogs/:id - Delete a blog post.
 */
export const deleteBlogById = async (req, res) => {
    const { id: blogId } = req.params;
    const userId = req.user.userId;

    try {
        // 1. Check ownership and get image_url
        const checkResult = await findBlogForUpdateOrDelete(blogId);
        if (!checkResult) {
            return res.status(404).json({ error: 'Blog post not found.' });
        }
        
        const postOwnerId = checkResult.user_id;
        if (postOwnerId !== userId) {
            return res.status(403).json({ error: 'Permission denied. You can only delete your own posts.' });
        }

        const oldImagePath = checkResult.image_url;

        // 2. Delete the database entry
        await deleteBlog(blogId, userId);
        
        // 3. Delete the associated file from the server disk if it exists
        if (oldImagePath && fs) {
            const absoluteOldImagePath = path.isAbsolute(oldImagePath) 
                ? oldImagePath 
                : path.join(path.resolve(), oldImagePath);
                
            fs.unlink(absoluteOldImagePath, err => {
                if (err) console.error(`Failed to delete file: ${absoluteOldImagePath}`, err);
            });
        }

        res.status(200).json({ message: `Blog post with ID ${blogId} deleted successfully.` });
    } catch (err) {
        console.error('Error deleting blog post:', err.message);
        res.status(500).json({ error: 'Internal server error while deleting blog post.' });
    }
};
